### PR TITLE
Added Other categories to UNIVERSITIES and PROGRAMMES

### PR DESCRIPTION
**Pull request by isakcodes**
Distinction within/outside EU/EEC

### CODE REVIEW

**Comment by isakcodes** [comment]
@oriolclosa have implemented the requested. Took all day! Should work.

I also saw an issue with fields resetting to defaults, addressed in issue #55

**Comment by isakcodes** [comment]
Okay now my build is not passing but it seems to be because of Black exiting with 1 status

**Comment by isakcodes** [comment]
Okay finally done

**Comment by oriolclosa** [comment]
Hej @isakcodes, made some minor changes to simplify, looks great, good work! You can check what I've done if you want and merge it afterwards. In the future we will start adding tests so features like this will need to have some coverage but it's ok by now.

**Pull request merged**
